In [1]:
import numpy as np
from numpy import linalg

In [2]:
N = 15
x = np.arange(N)[::-1]
print(x)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [3]:
N = 25
x = np.arange(N)[::-1].reshape((5,5))
print(x)
print(sum(np.diagonal(x)))


[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
60


In [4]:
"""Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3"""
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [5]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [7]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [9]:
cosinuses = []
for i in range(10):
    cosinuses.append(cosine(users_stats[i],next_user_stats))

print('User ID:',cosinuses.index(max(cosinuses))+1)

User ID: 8
